services:
  backend:
    build:
      context: ./weather-app-backend
      network: host
    container_name: meteops-backend
    network_mode: host
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    restart: unless-stopped
  frontend:
    build:
      context: ./weather-app-frontend
      network: host
    container_name: meteops-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
