services:
  backend:
    build:
      context: ./weather-app-backend
      network: host
    container_name: meteops-backend
    ports:
      - "3001:3001"
    env_file:
      - .env
    restart: unless-stopped

  frontend:
    build:
      context: ./weather-app-frontend
      network: host
    container_name: meteops-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
